apiVersion: v1
kind: Namespace
metadata:
  name: leader-election
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leader-election-sa
  namespace: leader-election
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leader-election
  namespace: leader-election
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election
  namespace: leader-election
subjects:
- kind: ServiceAccount
  name: leader-election-sa
  namespace: leader-election
roleRef:
  kind: Role 
  name: leader-election
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-election-test
  namespace: leader-election
spec:
  selector:
    matchLabels:
      app: leader-election-test
  template:
    metadata:
      labels:
        app: leader-election-test
    spec:
      containers:
      - name: leader-election-test
        image: patnaikshekhar/leader-election-test:1
      - name: leader-election-server
        image: patnaikshekhar/leader-election-sidecar:1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: leader-election-sa
